name: python

# workflow triggers
on:
  push:
    branches:
      - '**' # every branch
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  formatter:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: code formatter
        run: |
          pip install wheel
          pip install black
          black --check .
          black --check tests/

  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install packages
        run: |
          pip install wheel
          pip install -r requirements.txt
      - name: unittest
        run: |
          python -m unittest discover -b
